AllCops:
  TargetRubyVersion: 2.6
  # Ignore test script
  Exclude:
    - !ruby/regexp /ztestscript\.rb$/

# Ignore mix of compact and nested styles
Style/ClassAndModuleChildren:
  Exclude:
    - 'lib/sciolyff/interpreter/event.rb'
    - 'lib/sciolyff/interpreter/model.rb'
    - 'lib/sciolyff/interpreter/penalty.rb'
    - 'lib/sciolyff/interpreter/placing.rb'
    - 'lib/sciolyff/interpreter/team.rb'
    - 'lib/sciolyff/interpreter/tournament.rb'



