AllCops:
  TargetRubyVersion: 2.7
  # Ignore test script
  Exclude:
    - !ruby/regexp /ztestscript\.rb$/

# Ignore mix of compact and nested styles
Style/ClassAndModuleChildren:
  Exclude:
    - 'lib/sciolyff/interpreter/*'
    - 'lib/sciolyff/validator/*'

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Lint/RaiseException:
  Enabled: true

Lint/StructNewOverride:
  Enabled: true
